/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package PRINCIPAL;

/**
 *
 * @author USER
 */
import trabajofinal.peliculainterfaz;
import javax.swing.table.DefaultTableModel;
public class Administrador extends javax.swing.JInternalFrame {
     private DefaultTableModel model;
     private String[] header={"idpelicula" ," nombre" , "genero" , "cartelera" , "clasificaion"};
    private Object JTABLE;
    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();
        initTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtGenero = new javax.swing.JTextField();
        txtCartelera = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtidpelicula = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtClasificacion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable = new javax.swing.JTable();
        btnInsertar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtEliminarTodo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextfila = new javax.swing.JTextField();
        jTextcolumna = new javax.swing.JTextField();
        jTextdato = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Administrador");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("GENERO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel2.setText("NOMBRE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel1.setText("ID PELICULA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        txtGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGeneroActionPerformed(evt);
            }
        });
        jPanel1.add(txtGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 100, -1));
        jPanel1.add(txtCartelera, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 100, -1));

        jLabel4.setText("CARTELERA");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        txtidpelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidpeliculaActionPerformed(evt);
            }
        });
        jPanel1.add(txtidpelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 100, -1));

        jLabel5.setText("CLASIFICACION");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));
        jPanel1.add(txtClasificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 100, -1));

        JTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID PELICULA", "NOMBRE", "GENERO", "CARTELERA", "CLASIFICACION"
            }
        ));
        jScrollPane1.setViewportView(JTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 500, 260));

        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        jPanel1.add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, -1, -1));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, -1, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, -1, -1));

        txtEliminarTodo.setText("Eliminar Todo");
        txtEliminarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEliminarTodoActionPerformed(evt);
            }
        });
        jPanel1.add(txtEliminarTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, -1, -1));

        jButton1.setText("volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 730, -1, -1));

        jLabel6.setText("FILA");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, -1, -1));

        jLabel7.setText("COLUMNA");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, -1, -1));

        jLabel8.setText("NUEVO DATO");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, -1, -1));
        jPanel1.add(jTextfila, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 100, -1));

        jTextcolumna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextcolumnaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextcolumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 100, -1));
        jPanel1.add(jTextdato, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 100, -1));

        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 100, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabajofinal/ajustes.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 50, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeneroActionPerformed
        // TODO add your handling code her
                                       
    }//GEN-LAST:event_txtGeneroActionPerformed

    private void txtidpeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidpeliculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidpeliculaActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        // TODO add your handling code here:
       String idpelicula = txtidpelicula.getText();
         String nombre = txtnombre.getText();
         String genero =txtGenero.getText();
         String cartelera = txtCartelera.getText();
         String clasificacion = txtClasificacion.getText();  
        
      peliculainterfaz p = new  peliculainterfaz(idpelicula,nombre,genero,cartelera,clasificacion);
      model.addRow(p.toArray());
      txtidpelicula.setText("");
      txtnombre.setText("");
      txtGenero.setText("");
      txtCartelera.setText("");
      txtClasificacion.setText("");
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

         if (JTable.getSelectedRowCount()!=1){
             return;
         }
         int fila =JTable.getSelectedRow();
         model.removeRow(fila);
    }//GEN-LAST:event_btnEliminarActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextcolumnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextcolumnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextcolumnaActionPerformed
     
    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_txtnombreActionPerformed

    private void txtEliminarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEliminarTodoActionPerformed
                int filas = JTable.getRowCount();
                for(int i =filas -1 ; i>=0; i--){
                    model.removeRow(i);
                }       
    }//GEN-LAST:event_txtEliminarTodoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
       int fila=Integer.parseInt(jTextfila.getText());
       int columna=Integer.parseInt(jTextcolumna.getText());
        model.setValueAt(jTextdato.getText() , fila, columna);
        
    }//GEN-LAST:event_btnModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTable;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextcolumna;
    private javax.swing.JTextField jTextdato;
    private javax.swing.JTextField jTextfila;
    private javax.swing.JTextField txtCartelera;
    private javax.swing.JTextField txtClasificacion;
    private javax.swing.JButton txtEliminarTodo;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtidpelicula;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables

    private void initTable() {
    model = new DefaultTableModel(header, 0){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        JTable.setModel(model);
    }     
            
    }
     


