/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package PRINCIPAL;
import javax.swing.*;
import java.io.*;
/**
 *
 * @author USER
 */
public class empleado extends javax.swing.JInternalFrame {

    /**
     * Creates new form empleado
     */
    public empleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        deployPelicula = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cantidadNIno = new javax.swing.JTextField();
        cantidadAdulto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbEfectivo = new javax.swing.JCheckBox();
        cbTarjeta = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        deployHorario = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        pagoRealizado = new javax.swing.JTextField();
        btnCalcularCAmbio = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        lbTotalPago = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        btnProcesar = new javax.swing.JButton();
        lbMensajeOferta = new javax.swing.JLabel();
        lbCambio = new javax.swing.JLabel();
        lbRegistrar = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Empleado");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("PELICULA");

        deployPelicula.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Oppenheimer", "Los asesinos de la luna", "John wick 4", "Spiderman: Cruzando el Multiverso", "Barbie", "TAR", "Mision imposible: Sentencia Mortal", "Super Mario Bros", "Los Fobelman", "FNAF" }));
        deployPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deployPeliculaActionPerformed(evt);
            }
        });

        jLabel2.setText("BOLETO");

        jLabel5.setText("CANTIDAD");

        cantidadNIno.setName(""); // NOI18N
        cantidadNIno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadNInoActionPerformed(evt);
            }
        });

        jLabel7.setText("Forma de pago");

        cbEfectivo.setText("Efectivo");
        cbEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEfectivoActionPerformed(evt);
            }
        });

        cbTarjeta.setText("Tarjeta");
        cbTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTarjetaActionPerformed(evt);
            }
        });

        jLabel10.setText("HORA");

        deployHorario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10:00 - 12:00 am", "12:20 -  2:20  pm", "8:00 -  10:00  am" }));

        jLabel22.setText("Dinero Recibido");

        btnCalcularCAmbio.setText("Calcular Cambio");
        btnCalcularCAmbio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularCAmbioActionPerformed(evt);
            }
        });

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabajofinal/Oppenhimer-.jpg"))); // NOI18N

        jLabel4.setText("Niño");

        jLabel24.setText("Adulto");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabajofinal/empleado.png"))); // NOI18N

        jLabel25.setText("CANTIDAD");

        jLabel26.setText("BOLETO");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel27.setText("TOTAL");

        lbTotalPago.setText("S/ 00.00");

        jLabel8.setText("S/12.00 c/u");

        jLabel28.setText("S/16.00 c/u");

        jLabel29.setText("->");

        btnProcesar.setText("Procesar");
        btnProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarActionPerformed(evt);
            }
        });

        lbMensajeOferta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMensajeOferta.setText("No ha seleccionado ningún metodo de pago");
        lbMensajeOferta.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lbCambio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCambio.setText("S/ --.--");

        lbRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbRegistrar.setText("No ha seleccionado ningún metodo de pago");
        lbRegistrar.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel27)
                                .addGap(18, 18, 18)
                                .addComponent(lbTotalPago, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jLabel29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addComponent(jLabel7))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(cbEfectivo)
                                        .addGap(36, 36, 36)
                                        .addComponent(cbTarjeta))))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel4))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel10))
                                            .addGap(24, 24, 24)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(deployPelicula, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel5)
                                                                .addComponent(cantidadNIno, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                    .addGap(6, 6, 6)
                                                                    .addComponent(jLabel8)))
                                                            .addGap(25, 25, 25)
                                                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel26)
                                                                .addComponent(jLabel24))
                                                            .addGap(25, 25, 25)
                                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(cantidadAdulto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel25)
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                    .addGap(6, 6, 6)
                                                                    .addComponent(jLabel28))))
                                                        .addComponent(deployHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(0, 0, Short.MAX_VALUE))))
                                        .addComponent(jSeparator2)
                                        .addComponent(lbMensajeOferta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(145, 145, 145)
                                        .addComponent(btnProcesar))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(81, 81, 81)
                                        .addComponent(jLabel22)
                                        .addGap(28, 28, 28)
                                        .addComponent(pagoRealizado, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(129, 129, 129)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnCalcularCAmbio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lbCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(btnRegistrar))
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(116, 116, 116))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegistrar)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(lbRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(deployPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(deployHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel25))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(cantidadNIno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cantidadAdulto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel28)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnProcesar)
                        .addGap(12, 12, 12)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addGap(7, 7, 7)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbTarjeta)
                                    .addComponent(cbEfectivo)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel27)
                                    .addComponent(lbTotalPago)
                                    .addComponent(jLabel29))))
                        .addGap(18, 18, 18)
                        .addComponent(lbMensajeOferta, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(pagoRealizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnCalcularCAmbio)
                        .addGap(18, 18, 18)
                        .addComponent(lbCambio)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deployPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deployPeliculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deployPeliculaActionPerformed
    

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cantidadNInoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadNInoActionPerformed
        
    }//GEN-LAST:event_cantidadNInoActionPerformed
    double globalPago = 0;
    double globalPagoTemp = 0;
    int metodoPagoGlob = 0;
    private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed
        int sumNIno = Integer.parseInt( cantidadNIno.getText());
        int sumAdulto = Integer.parseInt( cantidadAdulto.getText());
        double totalPago = (sumNIno* 12) + (sumAdulto*16);
        lbTotalPago.setText("S/ " + String.valueOf(totalPago));
        globalPago = totalPago;
        globalPagoTemp = totalPago;
    }//GEN-LAST:event_btnProcesarActionPerformed

    private void cbEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEfectivoActionPerformed
       cbTarjeta.setSelected(false);
       cbEfectivo.setSelected(true);
       lbMensajeOferta.setText("No se aplica Ningun descuento al pagar con efectivo");
       globalPago = globalPagoTemp;
       metodoPagoGlob = 1;
    }//GEN-LAST:event_cbEfectivoActionPerformed
    
    double discount;
    private void cbTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTarjetaActionPerformed
       cbEfectivo.setSelected(false);
       cbTarjeta.setSelected(true);
       discount = globalPago -  (globalPago * 0.05);
       lbMensajeOferta.setText("<html>Al pagar con tarjeta se le aplicará 5% de descuento <br> PRECIO CON DESCUENTO: S/ " + discount  + "<br></html>");
       globalPago = discount;
       metodoPagoGlob = 2;
    }//GEN-LAST:event_cbTarjetaActionPerformed

    private static final String archivoData = "ticketData.txt";

    public static void guardarTicketData(String pelicula, String horario, int ticketsNinos, int ticketsAdultos, double pagoTotalEsc, int metodoDePago, JLabel a) {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(archivoData, true))) {
            if (pelicula.isEmpty() || horario.isEmpty() ||  pagoTotalEsc == 0 || metodoDePago == 0) {
                 a.setText("Error registrando los datos de la compra");
            } else {
                 writer.write("Pelicula: " + pelicula + "\tHorario: " + horario + "\tCantidad Niños: " + ticketsNinos + "\tCantidad Adultos: " + ticketsAdultos +  "\tPago total: " + pagoTotalEsc + "\tTipo de pago: " + metodoDePago + "\n");
                  a.setText("Registro guardado exitosamente.");
            }
           

        } catch (IOException e) {
            a.setText("Error registrando los datos de la compra" + e.getMessage());
        }
    }
    
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        guardarTicketData( String.valueOf(deployPelicula.getSelectedItem()),   String.valueOf(deployHorario.getSelectedItem()), Integer.parseInt( cantidadNIno.getText()),  Integer.parseInt( cantidadAdulto.getText()),  globalPago, metodoPagoGlob, lbRegistrar);
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnCalcularCAmbioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularCAmbioActionPerformed
        double p =Integer.parseInt( pagoRealizado.getText());
        lbCambio.setText( String.valueOf(p - globalPago));
    }//GEN-LAST:event_btnCalcularCAmbioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularCAmbio;
    private javax.swing.JButton btnProcesar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JTextField cantidadAdulto;
    private javax.swing.JTextField cantidadNIno;
    private javax.swing.JCheckBox cbEfectivo;
    private javax.swing.JCheckBox cbTarjeta;
    private javax.swing.JComboBox<String> deployHorario;
    private javax.swing.JComboBox<String> deployPelicula;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbCambio;
    private javax.swing.JLabel lbMensajeOferta;
    private javax.swing.JLabel lbRegistrar;
    private javax.swing.JLabel lbTotalPago;
    private javax.swing.JTextField pagoRealizado;
    // End of variables declaration//GEN-END:variables
}
